In [1]:
"""1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?"""

'1. Write a Python Program to Add Two Matrices?\n2. Write a Python Program to Multiply Two Matrices?\n3. Write a Python Program to Transpose a Matrix?\n4. Write a Python Program to Sort Words in Alphabetic Order?\n5. Write a Python Program to Remove Punctuation From a String?'

In [4]:
#1.
import numpy as np

a = np.array([[2,3,5],
              [5,6,9],
              [5,2,1]])
b = np.array([[6,9,5],
              [5,4,6],
              [8,7,4]])
msum = np.add(a,b)
print("sum of a and b matrices is  \n",msum)

sum of a and b matrices is  
 [[ 8 12 10]
 [10 10 15]
 [13  9  5]]


In [5]:
2.
a = np.array([[2,3,5],
              [5,6,9],
              [5,2,1]])
b = np.array([[6,9,5],
              [5,4,6],
              [8,7,4]])
mprod = np.dot(a,b)
print("product of 2 matrices is \n",mprod)

product of 2 matrices is 
 [[ 67  65  48]
 [132 132  97]
 [ 48  60  41]]


In [9]:
#3.

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[0,0],[0,0],[0,0]])
for i in range(len(a)):
    for j in range(len(a[0])):
        b[j][i] = a[i][j]
for transpose in b:
    print(transpose)

[1 4]
[2 5]
[3 6]


In [10]:
#4.
a = input("enter")
alp_ord = a.split()
alp_ord.sort()
for i in alp_ord:
    print(i)

enter hello my champ


champ
hello
my


In [12]:
#5.
collections = ".,@!#$%^&*"
a = "hey, how are you"
b = ""
for i in a:
    if i not in collections:
        b = b+i
print(b)

hey how are you
